import type { z } from "zod";
import type { RouteContract } from "./common";
import {
  browserAttachCurrentWindowRoute,
  browserClearSandboxDataRoute,
  browserDestroyRoute,
  browserDetachRoute,
  browserGetStatusRoute,
  browserGoBackRoute,
  browserGoForwardRoute,
  browserLoadUrlRoute,
  browserReloadRoute,
  browserUpdateCurrentWindowBoundsRoute,
} from "./routes/browser.routes";
import {
  chatRespondToolInteractionRoute,
  chatSendMessageRoute,
  chatSteerActiveTurnRoute,
  chatStopStreamRoute,
} from "./routes/chat.routes";
import {
  databaseSecurityChangePasswordRoute,
  databaseSecurityDiagnoseSchemaRoute,
  databaseSecurityDisableRoute,
  databaseSecurityEnableRoute,
  databaseSecurityGetStatusRoute,
  databaseSecurityRepairSchemaRoute,
} from "./routes/database-security.routes";
import {
  configAddCustomPromptRoute,
  configAddSystemPromptRoute,
  configClearDefaultSystemPromptRoute,
  configDeleteCustomPromptRoute,
  configDeleteSystemPromptRoute,
  configGetAcpRegistryIconMarkupRoute,
  configGetAcpSharedMcpSelectionsRoute,
  configGetAcpStateRoute,
  configGetAgentMcpSelectionsRoute,
  configGetAwsBedrockCredentialRoute,
  configGetAzureApiVersionRoute,
  configGetDefaultProjectPathRoute,
  configGetDefaultSystemPromptRoute,
  configGetEntriesRoute,
  configGetFloatingButtonRoute,
  configGetGeminiSafetyRoute,
  configGetKnowledgeConfigsRoute,
  configGetLanguageRoute,
  configGetMcpServersRoute,
  configGetShortcutKeysRoute,
  configGetSyncSettingsRoute,
  configGetSystemPromptsRoute,
  configGetThemeRoute,
  configGetVoiceAiConfigRoute,
  configListAgentsRoute,
  configListCustomPromptsRoute,
  configResetDefaultSystemPromptRoute,
  configResetShortcutKeysRoute,
  configResolveArgosAgentConfigRoute,
  configSetAcpSharedMcpSelectionsRoute,
  configSetAwsBedrockCredentialRoute,
  configSetAzureApiVersionRoute,
  configSetCustomPromptsRoute,
  configSetDefaultProjectPathRoute,
  configSetDefaultSystemPromptIdRoute,
  configSetDefaultSystemPromptRoute,
  configSetFloatingButtonRoute,
  configSetGeminiSafetyRoute,
  configSetKnowledgeConfigsRoute,
  configSetLanguageRoute,
  configSetShortcutKeysRoute,
  configSetSystemPromptsRoute,
  configSetThemeRoute,
  configUpdateCustomPromptRoute,
  configUpdateEntriesRoute,
  configUpdateSyncSettingsRoute,
  configUpdateSystemPromptRoute,
  configUpdateVoiceAiConfigRoute,
} from "./routes/config.routes";
import { dialogErrorRoute, dialogRespondRoute } from "./routes/dialog.routes";
import {
  deviceGetAppVersionRoute,
  deviceGetInfoRoute,
  deviceRestartAppRoute,
  deviceSanitizeSvgRoute,
  deviceSelectDirectoryRoute,
} from "./routes/device.routes";
import {
  fileCopyImageRoute,
  fileGetMimeTypeRoute,
  fileIsDirectoryRoute,
  filePrepareDirectoryRoute,
  filePrepareFileRoute,
  fileReadFileRoute,
  fileSaveImageRoute,
  fileWriteImageBase64Route,
} from "./routes/file.routes";
import {
  mcpAddServerRoute,
  mcpCallToolRoute,
  mcpCancelSamplingRequestRoute,
  mcpClearNpmRegistryCacheRoute,
  mcpGetClientsRoute,
  mcpGetEnabledRoute,
  mcpGetMcpRouterApiKeyRoute,
  mcpGetNpmRegistryStatusRoute,
  mcpGetPromptRoute,
  mcpGetServersRoute,
  mcpInstallMcpRouterServerRoute,
  mcpIsServerInstalledRoute,
  mcpIsServerRunningRoute,
  mcpListMcpRouterServersRoute,
  mcpListPromptsRoute,
  mcpListResourcesRoute,
  mcpListToolDefinitionsRoute,
  mcpReadResourceRoute,
  mcpRefreshNpmRegistryRoute,
  mcpRemoveServerRoute,
  mcpSetAutoDetectNpmRegistryRoute,
  mcpSetCustomNpmRegistryRoute,
  mcpSetEnabledRoute,
  mcpSetMcpRouterApiKeyRoute,
  mcpSetServerEnabledRoute,
  mcpStartServerRoute,
  mcpStopServerRoute,
  mcpSubmitSamplingDecisionRoute,
  mcpUpdateMcpRouterServersAuthRoute,
  mcpUpdateServerRoute,
} from "./routes/mcp.routes";
import {
  modelsAddCustomRoute,
  modelsExportConfigsRoute,
  modelsGetCapabilitiesRoute,
  modelsGetConfigRoute,
  modelsGetProviderCatalogRoute,
  modelsGetProviderConfigsRoute,
  modelsHasUserConfigRoute,
  modelsImportConfigsRoute,
  modelsListRuntimeRoute,
  modelsRemoveCustomRoute,
  modelsResetConfigRoute,
  modelsSetBatchStatusRoute,
  modelsSetConfigRoute,
  modelsSetStatusRoute,
  modelsTranscribeAudioRoute,
  modelsUpdateCustomRoute,
} from "./routes/models.routes";
import {
  onboardingCompleteRoute,
  onboardingGetStateRoute,
  onboardingResetRoute,
  onboardingSetStepStatusRoute,
  onboardingStartRoute,
} from "./routes/onboarding.routes";
import {
  scheduledTasksDeleteRoute,
  scheduledTasksFireNowRoute,
  scheduledTasksListRoute,
  scheduledTasksToggleRoute,
  scheduledTasksUpsertRoute,
} from "./routes/scheduledTasks.routes";
import {
  providersAddRoute,
  providersGetAcpProcessConfigOptionsRoute,
  providersGetRateLimitStatusRoute,
  providersImportApplyRoute,
  providersImportScanRoute,
  providersListDefaultsRoute,
  providersListModelsRoute,
  providersListOllamaModelsRoute,
  providersListOllamaRunningModelsRoute,
  providersListRoute,
  providersListSummariesRoute,
  providersPullOllamaModelRoute,
  providersRefreshModelsRoute,
  providersRemoveRoute,
  providersReorderRoute,
  providersSetByIdRoute,
  providersTestConnectionRoute,
  providersUpdateRoute,
  providersWarmupAcpProcessRoute,
} from "./routes/providers.routes";
import {
  projectListEnvironmentsRoute,
  projectListRecentRoute,
  projectOpenDirectoryRoute,
  projectSelectDirectoryRoute,
} from "./routes/project.routes";
import {
  pluginsDisableRoute,
  pluginsEnableRoute,
  pluginsGetRoute,
  pluginsInvokeActionRoute,
  pluginsListRoute,
} from "./routes/plugins.routes";
import {
  settingsActivityListRoute,
  settingsGetSnapshotRoute,
  settingsListSystemFontsRoute,
  settingsUpdateRoute,
} from "./routes/settings.routes";
import { startupGetBootstrapRoute } from "./routes/startup.routes";
import {
  sessionsActivateRoute,
  sessionsClearMessagesRoute,
  sessionsCompactRoute,
  sessionsConvertPendingInputToSteerRoute,
  sessionsCreateRoute,
  sessionsDeleteAgentSessionsRoute,
  sessionsDeleteMessageRoute,
  sessionsDeletePendingInputRoute,
  sessionsDeleteRoute,
  sessionsDeactivateRoute,
  sessionsEditUserMessageRoute,
  sessionsEnsureAcpDraftRoute,
  sessionsExportRoute,
  sessionsForkRoute,
  sessionsGetAcpSessionCommandsRoute,
  sessionsGetAcpSessionConfigOptionsRoute,
  sessionsGetActiveRoute,
  sessionsGetAgentsRoute,
  sessionsGetAgentTransferImpactRoute,
  sessionsGetDisabledAgentToolsRoute,
  sessionsGetLightweightByIdsRoute,
  sessionsGetGenerationSettingsRoute,
  sessionsGetPermissionModeRoute,
  sessionsGetSearchResultsRoute,
  sessionsListLightweightRoute,
  sessionsListMessagesPageRoute,
  sessionsListRoute,
  sessionsGetViewManifestsRoute,
  sessionsListMessageTracesRoute,
  sessionsListPendingInputsRoute,
  sessionsMoveAgentSessionsRoute,
  sessionsMoveQueuedInputRoute,
  sessionsMoveToAgentRoute,
  sessionsQueuePendingInputRoute,
  sessionsRenameRoute,
  sessionsRetryMessageRoute,
  sessionsRestoreRoute,
} from "./routes/sessions.routes";
import {
  sessionsSearchHistoryRoute,
  sessionsSetAcpSessionConfigOptionRoute,
  sessionsSetModelRoute,
  sessionsSetPermissionModeRoute,
  sessionsSetProjectDirRoute,
  sessionsSetSubagentEnabledRoute,
  sessionsSteerPendingInputRoute,
  sessionsTogglePinnedRoute,
  sessionsTranslateTextRoute,
  sessionsUpdateDisabledAgentToolsRoute,
  sessionsUpdateGenerationSettingsRoute,
  sessionsUpdateQueuedInputRoute,
} from "./routes/sessions.routes";
import {
  skillsGetActiveRoute,
  skillsGetDirectoryRoute,
  skillsGetExtensionRoute,
  skillsGetFolderTreeRoute,
  skillsInstallFromFolderRoute,
  skillsInstallFromUrlRoute,
  skillsInstallFromZipRoute,
  skillsListMetadataRoute,
  skillsListScriptsRoute,
  skillsOpenFolderRoute,
  skillsSaveExtensionRoute,
  skillsSaveWithExtensionRoute,
  skillsSetActiveRoute,
  skillsUninstallRoute,
  skillsUpdateFileRoute,
} from "./routes/skills.routes";
import {
  syncGetBackupStatusRoute,
  syncImportRoute,
  syncListBackupsRoute,
  syncOpenFolderRoute,
  syncStartBackupRoute,
  syncGetCloudConfigRoute,
  syncSetCloudConfigRoute,
  syncTestCloudRoute,
  syncUploadToCloudRoute,
  syncPullFromCloudRoute,
} from "./routes/sync.routes";
import {
  systemOpenSettingsRoute,
  systemConsumePendingProviderInstallRoute,
  systemSetPendingProviderInstallRoute,
} from "./routes/system.routes";
import { toolsListDefinitionsRoute } from "./routes/tools.routes";
import {
  tabCaptureCurrentAreaRoute,
  tabNotifyRendererActivatedRoute,
  tabNotifyRendererReadyRoute,
  tabStitchImagesWithWatermarkRoute,
} from "./routes/tab.routes";
import {
  upgradeCheckRoute,
  upgradeClearMockRoute,
  upgradeGetStatusRoute,
  upgradeMockDownloadedRoute,
  upgradeOpenDownloadRoute,
  upgradeRestartToUpdateRoute,
  upgradeStartDownloadRoute,
} from "./routes/upgrade.routes";
import {
  windowCloseCurrentRoute,
  windowCloseFloatingCurrentRoute,
  windowGetCurrentStateRoute,
  windowMinimizeCurrentRoute,
  windowPreviewFileRoute,
  windowToggleMaximizeCurrentRoute,
} from "./routes/window.routes";
import {
  workspaceExpandDirectoryRoute,
  workspaceGetGitDiffRoute,
  workspaceGetGitStatusRoute,
  workspaceOpenFileRoute,
  workspaceReadDirectoryRoute,
  workspaceReadFilePreviewRoute,
  workspaceRegisterRoute,
  workspaceResolveMarkdownLinkedFileRoute,
  workspaceRevealFileInFolderRoute,
  workspaceSearchFilesRoute,
  workspaceUnregisterRoute,
  workspaceUnwatchRoute,
  workspaceWatchRoute,
} from "./routes/workspace.routes";

export * from "./routes/browser.routes";
export * from "./routes/chat.routes";
export * from "./routes/config.routes";
export * from "./routes/database-security.routes";
export * from "./routes/dialog.routes";
export * from "./routes/device.routes";
export * from "./routes/file.routes";
export * from "./routes/mcp.routes";
export * from "./routes/models.routes";
export * from "./routes/onboarding.routes";
export * from "./routes/plugins.routes";
export * from "./routes/providers.routes";
export * from "./routes/project.routes";
export * from "./routes/scheduledTasks.routes";
export * from "./routes/settings.routes";
export * from "./routes/startup.routes";
export * from "./routes/sessions.routes";
export * from "./routes/skills.routes";
export * from "./routes/sync.routes";
export * from "./routes/system.routes";
export * from "./routes/tab.routes";
export * from "./routes/tools.routes";
export * from "./routes/upgrade.routes";
export * from "./routes/window.routes";
export * from "./routes/workspace.routes";

export const ARGOS_ROUTE_CATALOG = {
  [windowGetCurrentStateRoute.name]: windowGetCurrentStateRoute,
  [windowMinimizeCurrentRoute.name]: windowMinimizeCurrentRoute,
  [windowToggleMaximizeCurrentRoute.name]: windowToggleMaximizeCurrentRoute,
  [windowCloseCurrentRoute.name]: windowCloseCurrentRoute,
  [windowCloseFloatingCurrentRoute.name]: windowCloseFloatingCurrentRoute,
  [windowPreviewFileRoute.name]: windowPreviewFileRoute,
  [deviceGetAppVersionRoute.name]: deviceGetAppVersionRoute,
  [deviceGetInfoRoute.name]: deviceGetInfoRoute,
  [deviceSelectDirectoryRoute.name]: deviceSelectDirectoryRoute,
  [deviceRestartAppRoute.name]: deviceRestartAppRoute,
  [deviceSanitizeSvgRoute.name]: deviceSanitizeSvgRoute,
  [projectListRecentRoute.name]: projectListRecentRoute,
  [projectListEnvironmentsRoute.name]: projectListEnvironmentsRoute,
  [projectOpenDirectoryRoute.name]: projectOpenDirectoryRoute,
  [projectSelectDirectoryRoute.name]: projectSelectDirectoryRoute,
  [onboardingGetStateRoute.name]: onboardingGetStateRoute,
  [onboardingStartRoute.name]: onboardingStartRoute,
  [onboardingSetStepStatusRoute.name]: onboardingSetStepStatusRoute,
  [onboardingCompleteRoute.name]: onboardingCompleteRoute,
  [onboardingResetRoute.name]: onboardingResetRoute,
  [scheduledTasksListRoute.name]: scheduledTasksListRoute,
  [scheduledTasksUpsertRoute.name]: scheduledTasksUpsertRoute,
  [scheduledTasksDeleteRoute.name]: scheduledTasksDeleteRoute,
  [scheduledTasksToggleRoute.name]: scheduledTasksToggleRoute,
  [scheduledTasksFireNowRoute.name]: scheduledTasksFireNowRoute,
  [pluginsListRoute.name]: pluginsListRoute,
  [pluginsGetRoute.name]: pluginsGetRoute,
  [pluginsEnableRoute.name]: pluginsEnableRoute,
  [pluginsDisableRoute.name]: pluginsDisableRoute,
  [pluginsInvokeActionRoute.name]: pluginsInvokeActionRoute,
  [fileGetMimeTypeRoute.name]: fileGetMimeTypeRoute,
  [filePrepareFileRoute.name]: filePrepareFileRoute,
  [filePrepareDirectoryRoute.name]: filePrepareDirectoryRoute,
  [fileReadFileRoute.name]: fileReadFileRoute,
  [fileIsDirectoryRoute.name]: fileIsDirectoryRoute,
  [fileWriteImageBase64Route.name]: fileWriteImageBase64Route,
  [fileSaveImageRoute.name]: fileSaveImageRoute,
  [fileCopyImageRoute.name]: fileCopyImageRoute,
  [workspaceRegisterRoute.name]: workspaceRegisterRoute,
  [workspaceUnregisterRoute.name]: workspaceUnregisterRoute,
  [workspaceWatchRoute.name]: workspaceWatchRoute,
  [workspaceUnwatchRoute.name]: workspaceUnwatchRoute,
  [workspaceReadDirectoryRoute.name]: workspaceReadDirectoryRoute,
  [workspaceExpandDirectoryRoute.name]: workspaceExpandDirectoryRoute,
  [workspaceRevealFileInFolderRoute.name]: workspaceRevealFileInFolderRoute,
  [workspaceOpenFileRoute.name]: workspaceOpenFileRoute,
  [workspaceReadFilePreviewRoute.name]: workspaceReadFilePreviewRoute,
  [workspaceResolveMarkdownLinkedFileRoute.name]: workspaceResolveMarkdownLinkedFileRoute,
  [workspaceGetGitStatusRoute.name]: workspaceGetGitStatusRoute,
  [workspaceGetGitDiffRoute.name]: workspaceGetGitDiffRoute,
  [workspaceSearchFilesRoute.name]: workspaceSearchFilesRoute,
  [browserGetStatusRoute.name]: browserGetStatusRoute,
  [browserLoadUrlRoute.name]: browserLoadUrlRoute,
  [browserAttachCurrentWindowRoute.name]: browserAttachCurrentWindowRoute,
  [browserUpdateCurrentWindowBoundsRoute.name]: browserUpdateCurrentWindowBoundsRoute,
  [browserDetachRoute.name]: browserDetachRoute,
  [browserDestroyRoute.name]: browserDestroyRoute,
  [browserGoBackRoute.name]: browserGoBackRoute,
  [browserGoForwardRoute.name]: browserGoForwardRoute,
  [browserReloadRoute.name]: browserReloadRoute,
  [browserClearSandboxDataRoute.name]: browserClearSandboxDataRoute,
  [tabNotifyRendererReadyRoute.name]: tabNotifyRendererReadyRoute,
  [tabNotifyRendererActivatedRoute.name]: tabNotifyRendererActivatedRoute,
  [tabCaptureCurrentAreaRoute.name]: tabCaptureCurrentAreaRoute,
  [tabStitchImagesWithWatermarkRoute.name]: tabStitchImagesWithWatermarkRoute,
  [configGetEntriesRoute.name]: configGetEntriesRoute,
  [configUpdateEntriesRoute.name]: configUpdateEntriesRoute,
  [configGetLanguageRoute.name]: configGetLanguageRoute,
  [configSetLanguageRoute.name]: configSetLanguageRoute,
  [configGetThemeRoute.name]: configGetThemeRoute,
  [configSetThemeRoute.name]: configSetThemeRoute,
  [configGetFloatingButtonRoute.name]: configGetFloatingButtonRoute,
  [configSetFloatingButtonRoute.name]: configSetFloatingButtonRoute,
  [configGetSyncSettingsRoute.name]: configGetSyncSettingsRoute,
  [configUpdateSyncSettingsRoute.name]: configUpdateSyncSettingsRoute,
  [configGetDefaultProjectPathRoute.name]: configGetDefaultProjectPathRoute,
  [configSetDefaultProjectPathRoute.name]: configSetDefaultProjectPathRoute,
  [configGetShortcutKeysRoute.name]: configGetShortcutKeysRoute,
  [configSetShortcutKeysRoute.name]: configSetShortcutKeysRoute,
  [configResetShortcutKeysRoute.name]: configResetShortcutKeysRoute,
  [configListCustomPromptsRoute.name]: configListCustomPromptsRoute,
  [configSetCustomPromptsRoute.name]: configSetCustomPromptsRoute,
  [configAddCustomPromptRoute.name]: configAddCustomPromptRoute,
  [configUpdateCustomPromptRoute.name]: configUpdateCustomPromptRoute,
  [configDeleteCustomPromptRoute.name]: configDeleteCustomPromptRoute,
  [configGetSystemPromptsRoute.name]: configGetSystemPromptsRoute,
  [configSetSystemPromptsRoute.name]: configSetSystemPromptsRoute,
  [configAddSystemPromptRoute.name]: configAddSystemPromptRoute,
  [configUpdateSystemPromptRoute.name]: configUpdateSystemPromptRoute,
  [configDeleteSystemPromptRoute.name]: configDeleteSystemPromptRoute,
  [configGetDefaultSystemPromptRoute.name]: configGetDefaultSystemPromptRoute,
  [configSetDefaultSystemPromptRoute.name]: configSetDefaultSystemPromptRoute,
  [configResetDefaultSystemPromptRoute.name]: configResetDefaultSystemPromptRoute,
  [configClearDefaultSystemPromptRoute.name]: configClearDefaultSystemPromptRoute,
  [configSetDefaultSystemPromptIdRoute.name]: configSetDefaultSystemPromptIdRoute,
  [configGetAcpStateRoute.name]: configGetAcpStateRoute,
  [configListAgentsRoute.name]: configListAgentsRoute,
  [configResolveArgosAgentConfigRoute.name]: configResolveArgosAgentConfigRoute,
  [configGetAgentMcpSelectionsRoute.name]: configGetAgentMcpSelectionsRoute,
  [configGetAcpSharedMcpSelectionsRoute.name]: configGetAcpSharedMcpSelectionsRoute,
  [configSetAcpSharedMcpSelectionsRoute.name]: configSetAcpSharedMcpSelectionsRoute,
  [configGetMcpServersRoute.name]: configGetMcpServersRoute,
  [configGetKnowledgeConfigsRoute.name]: configGetKnowledgeConfigsRoute,
  [configSetKnowledgeConfigsRoute.name]: configSetKnowledgeConfigsRoute,
  [configGetAcpRegistryIconMarkupRoute.name]: configGetAcpRegistryIconMarkupRoute,
  [configGetVoiceAiConfigRoute.name]: configGetVoiceAiConfigRoute,
  [configUpdateVoiceAiConfigRoute.name]: configUpdateVoiceAiConfigRoute,
  [configGetGeminiSafetyRoute.name]: configGetGeminiSafetyRoute,
  [configSetGeminiSafetyRoute.name]: configSetGeminiSafetyRoute,
  [configGetAzureApiVersionRoute.name]: configGetAzureApiVersionRoute,
  [configSetAzureApiVersionRoute.name]: configSetAzureApiVersionRoute,
  [configGetAwsBedrockCredentialRoute.name]: configGetAwsBedrockCredentialRoute,
  [configSetAwsBedrockCredentialRoute.name]: configSetAwsBedrockCredentialRoute,
  [settingsGetSnapshotRoute.name]: settingsGetSnapshotRoute,
  [settingsListSystemFontsRoute.name]: settingsListSystemFontsRoute,
  [settingsUpdateRoute.name]: settingsUpdateRoute,
  [settingsActivityListRoute.name]: settingsActivityListRoute,
  [startupGetBootstrapRoute.name]: startupGetBootstrapRoute,
  [sessionsCreateRoute.name]: sessionsCreateRoute,
  [sessionsRestoreRoute.name]: sessionsRestoreRoute,
  [sessionsListMessagesPageRoute.name]: sessionsListMessagesPageRoute,
  [sessionsListRoute.name]: sessionsListRoute,
  [sessionsListLightweightRoute.name]: sessionsListLightweightRoute,
  [sessionsGetLightweightByIdsRoute.name]: sessionsGetLightweightByIdsRoute,
  [sessionsActivateRoute.name]: sessionsActivateRoute,
  [sessionsDeactivateRoute.name]: sessionsDeactivateRoute,
  [sessionsGetActiveRoute.name]: sessionsGetActiveRoute,
  [sessionsEnsureAcpDraftRoute.name]: sessionsEnsureAcpDraftRoute,
  [sessionsListPendingInputsRoute.name]: sessionsListPendingInputsRoute,
  [sessionsQueuePendingInputRoute.name]: sessionsQueuePendingInputRoute,
  [sessionsUpdateQueuedInputRoute.name]: sessionsUpdateQueuedInputRoute,
  [sessionsMoveQueuedInputRoute.name]: sessionsMoveQueuedInputRoute,
  [sessionsConvertPendingInputToSteerRoute.name]: sessionsConvertPendingInputToSteerRoute,
  [sessionsSteerPendingInputRoute.name]: sessionsSteerPendingInputRoute,
  [sessionsDeletePendingInputRoute.name]: sessionsDeletePendingInputRoute,
  [sessionsRetryMessageRoute.name]: sessionsRetryMessageRoute,
  [sessionsDeleteMessageRoute.name]: sessionsDeleteMessageRoute,
  [sessionsEditUserMessageRoute.name]: sessionsEditUserMessageRoute,
  [sessionsForkRoute.name]: sessionsForkRoute,
  [sessionsSearchHistoryRoute.name]: sessionsSearchHistoryRoute,
  [sessionsGetSearchResultsRoute.name]: sessionsGetSearchResultsRoute,
  [sessionsGetViewManifestsRoute.name]: sessionsGetViewManifestsRoute,
  [sessionsListMessageTracesRoute.name]: sessionsListMessageTracesRoute,
  [sessionsTranslateTextRoute.name]: sessionsTranslateTextRoute,
  [sessionsGetAgentsRoute.name]: sessionsGetAgentsRoute,
  [sessionsRenameRoute.name]: sessionsRenameRoute,
  [sessionsTogglePinnedRoute.name]: sessionsTogglePinnedRoute,
  [sessionsClearMessagesRoute.name]: sessionsClearMessagesRoute,
  [sessionsCompactRoute.name]: sessionsCompactRoute,
  [sessionsExportRoute.name]: sessionsExportRoute,
  [sessionsDeleteRoute.name]: sessionsDeleteRoute,
  [sessionsGetAgentTransferImpactRoute.name]: sessionsGetAgentTransferImpactRoute,
  [sessionsMoveAgentSessionsRoute.name]: sessionsMoveAgentSessionsRoute,
  [sessionsDeleteAgentSessionsRoute.name]: sessionsDeleteAgentSessionsRoute,
  [sessionsMoveToAgentRoute.name]: sessionsMoveToAgentRoute,
  [sessionsGetAcpSessionCommandsRoute.name]: sessionsGetAcpSessionCommandsRoute,
  [sessionsGetAcpSessionConfigOptionsRoute.name]: sessionsGetAcpSessionConfigOptionsRoute,
  [sessionsSetAcpSessionConfigOptionRoute.name]: sessionsSetAcpSessionConfigOptionRoute,
  [sessionsGetPermissionModeRoute.name]: sessionsGetPermissionModeRoute,
  [sessionsSetPermissionModeRoute.name]: sessionsSetPermissionModeRoute,
  [sessionsSetSubagentEnabledRoute.name]: sessionsSetSubagentEnabledRoute,
  [sessionsSetModelRoute.name]: sessionsSetModelRoute,
  [sessionsSetProjectDirRoute.name]: sessionsSetProjectDirRoute,
  [sessionsGetGenerationSettingsRoute.name]: sessionsGetGenerationSettingsRoute,
  [sessionsGetDisabledAgentToolsRoute.name]: sessionsGetDisabledAgentToolsRoute,
  [sessionsUpdateDisabledAgentToolsRoute.name]: sessionsUpdateDisabledAgentToolsRoute,
  [sessionsUpdateGenerationSettingsRoute.name]: sessionsUpdateGenerationSettingsRoute,
  [providersListRoute.name]: providersListRoute,
  [providersListSummariesRoute.name]: providersListSummariesRoute,
  [providersListDefaultsRoute.name]: providersListDefaultsRoute,
  [providersSetByIdRoute.name]: providersSetByIdRoute,
  [providersUpdateRoute.name]: providersUpdateRoute,
  [providersAddRoute.name]: providersAddRoute,
  [providersRemoveRoute.name]: providersRemoveRoute,
  [providersReorderRoute.name]: providersReorderRoute,
  [providersListModelsRoute.name]: providersListModelsRoute,
  [providersTestConnectionRoute.name]: providersTestConnectionRoute,
  [providersGetRateLimitStatusRoute.name]: providersGetRateLimitStatusRoute,
  [providersRefreshModelsRoute.name]: providersRefreshModelsRoute,
  [providersListOllamaModelsRoute.name]: providersListOllamaModelsRoute,
  [providersListOllamaRunningModelsRoute.name]: providersListOllamaRunningModelsRoute,
  [providersPullOllamaModelRoute.name]: providersPullOllamaModelRoute,
  [providersWarmupAcpProcessRoute.name]: providersWarmupAcpProcessRoute,
  [providersGetAcpProcessConfigOptionsRoute.name]: providersGetAcpProcessConfigOptionsRoute,
  [providersImportScanRoute.name]: providersImportScanRoute,
  [providersImportApplyRoute.name]: providersImportApplyRoute,
  [modelsGetProviderCatalogRoute.name]: modelsGetProviderCatalogRoute,
  [modelsListRuntimeRoute.name]: modelsListRuntimeRoute,
  [modelsSetBatchStatusRoute.name]: modelsSetBatchStatusRoute,
  [modelsSetStatusRoute.name]: modelsSetStatusRoute,
  [modelsAddCustomRoute.name]: modelsAddCustomRoute,
  [modelsRemoveCustomRoute.name]: modelsRemoveCustomRoute,
  [modelsUpdateCustomRoute.name]: modelsUpdateCustomRoute,
  [modelsGetConfigRoute.name]: modelsGetConfigRoute,
  [modelsSetConfigRoute.name]: modelsSetConfigRoute,
  [modelsResetConfigRoute.name]: modelsResetConfigRoute,
  [modelsGetProviderConfigsRoute.name]: modelsGetProviderConfigsRoute,
  [modelsHasUserConfigRoute.name]: modelsHasUserConfigRoute,
  [modelsExportConfigsRoute.name]: modelsExportConfigsRoute,
  [modelsImportConfigsRoute.name]: modelsImportConfigsRoute,
  [modelsGetCapabilitiesRoute.name]: modelsGetCapabilitiesRoute,
  [modelsTranscribeAudioRoute.name]: modelsTranscribeAudioRoute,
  [chatSendMessageRoute.name]: chatSendMessageRoute,
  [chatSteerActiveTurnRoute.name]: chatSteerActiveTurnRoute,
  [chatStopStreamRoute.name]: chatStopStreamRoute,
  [chatRespondToolInteractionRoute.name]: chatRespondToolInteractionRoute,
  [databaseSecurityGetStatusRoute.name]: databaseSecurityGetStatusRoute,
  [databaseSecurityEnableRoute.name]: databaseSecurityEnableRoute,
  [databaseSecurityChangePasswordRoute.name]: databaseSecurityChangePasswordRoute,
  [databaseSecurityDisableRoute.name]: databaseSecurityDisableRoute,
  [databaseSecurityDiagnoseSchemaRoute.name]: databaseSecurityDiagnoseSchemaRoute,
  [databaseSecurityRepairSchemaRoute.name]: databaseSecurityRepairSchemaRoute,
  [skillsListMetadataRoute.name]: skillsListMetadataRoute,
  [skillsGetDirectoryRoute.name]: skillsGetDirectoryRoute,
  [skillsInstallFromFolderRoute.name]: skillsInstallFromFolderRoute,
  [skillsInstallFromZipRoute.name]: skillsInstallFromZipRoute,
  [skillsInstallFromUrlRoute.name]: skillsInstallFromUrlRoute,
  [skillsUninstallRoute.name]: skillsUninstallRoute,
  [skillsUpdateFileRoute.name]: skillsUpdateFileRoute,
  [skillsSaveWithExtensionRoute.name]: skillsSaveWithExtensionRoute,
  [skillsGetFolderTreeRoute.name]: skillsGetFolderTreeRoute,
  [skillsOpenFolderRoute.name]: skillsOpenFolderRoute,
  [skillsGetExtensionRoute.name]: skillsGetExtensionRoute,
  [skillsSaveExtensionRoute.name]: skillsSaveExtensionRoute,
  [skillsListScriptsRoute.name]: skillsListScriptsRoute,
  [skillsGetActiveRoute.name]: skillsGetActiveRoute,
  [skillsSetActiveRoute.name]: skillsSetActiveRoute,
  [mcpGetServersRoute.name]: mcpGetServersRoute,
  [mcpGetEnabledRoute.name]: mcpGetEnabledRoute,
  [mcpGetClientsRoute.name]: mcpGetClientsRoute,
  [mcpListToolDefinitionsRoute.name]: mcpListToolDefinitionsRoute,
  [mcpListPromptsRoute.name]: mcpListPromptsRoute,
  [mcpListResourcesRoute.name]: mcpListResourcesRoute,
  [mcpCallToolRoute.name]: mcpCallToolRoute,
  [mcpAddServerRoute.name]: mcpAddServerRoute,
  [mcpUpdateServerRoute.name]: mcpUpdateServerRoute,
  [mcpRemoveServerRoute.name]: mcpRemoveServerRoute,
  [mcpSetServerEnabledRoute.name]: mcpSetServerEnabledRoute,
  [mcpSetEnabledRoute.name]: mcpSetEnabledRoute,
  [mcpIsServerRunningRoute.name]: mcpIsServerRunningRoute,
  [mcpStartServerRoute.name]: mcpStartServerRoute,
  [mcpStopServerRoute.name]: mcpStopServerRoute,
  [mcpGetPromptRoute.name]: mcpGetPromptRoute,
  [mcpReadResourceRoute.name]: mcpReadResourceRoute,
  [mcpSubmitSamplingDecisionRoute.name]: mcpSubmitSamplingDecisionRoute,
  [mcpCancelSamplingRequestRoute.name]: mcpCancelSamplingRequestRoute,
  [mcpGetNpmRegistryStatusRoute.name]: mcpGetNpmRegistryStatusRoute,
  [mcpRefreshNpmRegistryRoute.name]: mcpRefreshNpmRegistryRoute,
  [mcpSetCustomNpmRegistryRoute.name]: mcpSetCustomNpmRegistryRoute,
  [mcpSetAutoDetectNpmRegistryRoute.name]: mcpSetAutoDetectNpmRegistryRoute,
  [mcpClearNpmRegistryCacheRoute.name]: mcpClearNpmRegistryCacheRoute,
  [mcpListMcpRouterServersRoute.name]: mcpListMcpRouterServersRoute,
  [mcpInstallMcpRouterServerRoute.name]: mcpInstallMcpRouterServerRoute,
  [mcpGetMcpRouterApiKeyRoute.name]: mcpGetMcpRouterApiKeyRoute,
  [mcpSetMcpRouterApiKeyRoute.name]: mcpSetMcpRouterApiKeyRoute,
  [mcpIsServerInstalledRoute.name]: mcpIsServerInstalledRoute,
  [mcpUpdateMcpRouterServersAuthRoute.name]: mcpUpdateMcpRouterServersAuthRoute,
  [syncGetBackupStatusRoute.name]: syncGetBackupStatusRoute,
  [syncListBackupsRoute.name]: syncListBackupsRoute,
  [syncStartBackupRoute.name]: syncStartBackupRoute,
  [syncImportRoute.name]: syncImportRoute,
  [syncOpenFolderRoute.name]: syncOpenFolderRoute,
  [syncGetCloudConfigRoute.name]: syncGetCloudConfigRoute,
  [syncSetCloudConfigRoute.name]: syncSetCloudConfigRoute,
  [syncTestCloudRoute.name]: syncTestCloudRoute,
  [syncUploadToCloudRoute.name]: syncUploadToCloudRoute,
  [syncPullFromCloudRoute.name]: syncPullFromCloudRoute,
  [upgradeGetStatusRoute.name]: upgradeGetStatusRoute,
  [upgradeCheckRoute.name]: upgradeCheckRoute,
  [upgradeOpenDownloadRoute.name]: upgradeOpenDownloadRoute,
  [upgradeStartDownloadRoute.name]: upgradeStartDownloadRoute,
  [upgradeMockDownloadedRoute.name]: upgradeMockDownloadedRoute,
  [upgradeClearMockRoute.name]: upgradeClearMockRoute,
  [upgradeRestartToUpdateRoute.name]: upgradeRestartToUpdateRoute,
  [dialogRespondRoute.name]: dialogRespondRoute,
  [dialogErrorRoute.name]: dialogErrorRoute,
  [toolsListDefinitionsRoute.name]: toolsListDefinitionsRoute,
  [systemOpenSettingsRoute.name]: systemOpenSettingsRoute,
  [systemConsumePendingProviderInstallRoute.name]: systemConsumePendingProviderInstallRoute,
  [systemSetPendingProviderInstallRoute.name]: systemSetPendingProviderInstallRoute,
} satisfies Record<string, RouteContract>;

export type ArgosRouteCatalog = typeof ARGOS_ROUTE_CATALOG;
export type ArgosRouteName = keyof ArgosRouteCatalog;
export type ArgosRouteContract<T extends ArgosRouteName> = ArgosRouteCatalog[T];
export type ArgosRouteInput<T extends ArgosRouteName> = z.input<ArgosRouteContract<T>["input"]>;
export type ArgosRouteOutput<T extends ArgosRouteName> = z.output<ArgosRouteContract<T>["output"]>;

export function hasArgosRouteContract(name: string): name is ArgosRouteName {
  return Object.prototype.hasOwnProperty.call(ARGOS_ROUTE_CATALOG, name);
}

export function getArgosRouteContract<T extends ArgosRouteName>(name: T): ArgosRouteContract<T> {
  return ARGOS_ROUTE_CATALOG[name];
}
