/**
 * Connection runtime auth model types.
 *
 * See docs/architecture/connection-runtime-auth-model/ for the full specification.
 * These types are attached to every gated daemon request/connection.
 */

export type CredentialKind = "none" | "desktop-bootstrap" | "one-time-token" | "browser-session" | "bearer-session";

export type ExposureMode = "local-only" | "loopback-browser" | "network-accessible" | "relay";

export type AuthContext = {
  credentialKind: CredentialKind;
  sessionId?: string;
  exposureMode: ExposureMode;
  isLoopback: boolean;
};

export type AuthGateConfig = {
  exposureMode: ExposureMode;
  /** Desktop bootstrap secret generated by Electron main per sidecar launch. */
  desktopBootstrapSecret?: string;
};
