/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthGithubCallbackRouteImport } from "./routes/auth/github/callback";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: "/auth/github/callback",
  path: "/auth/github/callback",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth/github/callback": typeof AuthGithubCallbackRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth/github/callback": typeof AuthGithubCallbackRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/auth/github/callback": typeof AuthGithubCallbackRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/auth/github/callback";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/auth/github/callback";
  id: "__root__" | "/" | "/auth/github/callback";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/github/callback": {
      id: "/auth/github/callback";
      path: "/auth/github/callback";
      fullPath: "/auth/github/callback";
      preLoaderRoute: typeof AuthGithubCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
